import type { Lang } from "../core/types";

/** Diorama components in the NOC war room (see view.ts for their models). */
export type Component =
  | "edge"
  | "gw"
  | "k8s"
  | "cache"
  | "db"
  | "stream"
  | "cloud"
  | "cost"
  | "obs"
  | "ci"
  | "sec"
  | "ops";
export type L = Record<Lang, string>;
export type Sev = 1 | 2 | 3;

export interface Scenario {
  id: string;
  comp: Component;
  sev: Sev;
  /** Holographic metric over the component (language neutral). */
  metric: string;
  alert: L;
  options: [L, L, L, L];
  correct: number;
  /** Option worth half points (smaller burn). */
  partial?: number;
  explain: L;
  /** Multi-step incident: next question id after a correct answer (ok) or anything else (miss). */
  next?: { ok: string; miss: string };
  /** Follow-up step: never dealt from the deck, only reached through a parent's `next`. */
  step2?: true;
}

type P = [string, string];
interface X {
  c?: number;
  p?: number;
  next?: Scenario["next"];
  step2?: true;
}

const l = ([es, en]: P): L => ({ es, en });
const S = (
  id: string,
  comp: Component,
  sev: Sev,
  metric: string,
  alert: P,
  opts: P[],
  explain: P,
  x: X = {},
): Scenario => ({
  id,
  comp,
  sev,
  metric,
  alert: l(alert),
  options: opts.map(l) as Scenario["options"],
  correct: x.c ?? 0,
  partial: x.p,
  explain: l(explain),
  next: x.next,
  step2: x.step2,
});
const F: X = { step2: true };

export const SCENARIOS: Scenario[] = [
  // ── Networking, DNS, TLS ──────────────────────────────────────────────
  S(
    "dns",
    "edge",
    1,
    "SERVFAIL 41%",
    ["Fallos de resolución entre servicios", "Service-to-service lookups failing"],
    [
      ["Reiniciar todos los pods", "Restart every pod"],
      ["Revisar CoreDNS y ndots", "Check CoreDNS and ndots"],
      ["Culpar a la red", "Blame the network"],
      ["Escalar el LB", "Scale the LB"],
    ],
    ["DNS. Siempre es DNS. ndots:5 saturó CoreDNS.", "It's always DNS. ndots:5 flooded CoreDNS."],
    { c: 1 },
  ),
  S(
    "cert-3am",
    "gw",
    1,
    "TLS fail 100%",
    ["3:02am · TLS handshake falla en Kong", "3:02am · TLS handshakes failing on Kong"],
    [
      ["Renovar cert y rotar secret", "Renew cert, rotate secret"],
      ["Rollback de la app", "Roll back the app"],
      ["Escalar Kong", "Scale Kong"],
      ["Quitar HTTPS «un rato»", "Drop HTTPS «for a bit»"],
    ],
    [
      "Certificado vencido a las 3am: cert-manager apuntaba a staging.",
      "Cert expired at 3am: cert-manager pointed at staging.",
    ],
    { next: { ok: "cert-prevent", miss: "cert-ceo" } },
  ),
  S(
    "cert-prevent",
    "gw",
    3,
    "cert: 89d",
    ["Cert renovado. ¿Cómo evitas el próximo?", "Cert renewed. How do you stop the next one?"],
    [
      ["Alerta a 21 días + issuer de prod", "Alert at 21 days, prod issuer"],
      ["Cert de 10 años", "A 10-year cert"],
      ["Recordatorio en el calendario", "Calendar reminder"],
      ["Que lo renueve el de guardia", "On-call renews it by hand"],
    ],
    [
      "Alerta por expiración y el issuer correcto. El calendario renunció contigo.",
      "Expiry alerts and the right issuer. The calendar quits when you do.",
    ],
    { ...F, p: 2 },
  ),
  S(
    "cert-ceo",
    "gw",
    1,
    "down 25 min",
    ["Sigue caído y el CEO escribe en #general", "Still down; the CEO is posting in #general"],
    [
      ["Renovar cert; comms responde", "Renew cert; comms answers"],
      ["Responderle tú en detalle", "Reply to the CEO yourself"],
      ["Escalar Kong", "Scale Kong"],
      ["Silenciar #general", "Mute #general"],
    ],
    [
      "El IC arregla, comms comunica. Si tú respondes, nadie arregla.",
      "The IC fixes, comms talks. If you reply, nobody fixes.",
    ],
    { ...F, p: 1 },
  ),
  S(
    "dns-ttl",
    "edge",
    2,
    "old LB 40%",
    ["Migraste el LB y 40% sigue yendo al viejo", "LB migrated, 40% still hits the old one"],
    [
      ["Mantener el viejo hasta el TTL", "Keep the old one past the TTL"],
      ["Apagar el LB viejo ya", "Kill the old LB now"],
      ["Reiniciar los pods", "Restart the pods"],
      ["Cambiar de proveedor DNS", "Switch DNS providers"],
    ],
    [
      "TTL de 24h. DNS otra vez. Deja drenar antes de apagar.",
      "A 24h TTL. DNS again. Let it drain before shutting down.",
    ],
  ),
  S(
    "cdn-bypass",
    "edge",
    2,
    "origin RPS x20",
    ["El CDN dejó de cachear: origen x20", "CDN stopped caching: origin x20"],
    [
      ["Revisar Cache-Control y cookies", "Check Cache-Control and cookies"],
      ["Escalar el origen", "Scale the origin"],
      ["Rollback de la DB", "Roll back the DB"],
      ["Purgar todo el CDN", "Purge the whole CDN"],
    ],
    [
      "Un middleware agregó Set-Cookie a todo y el CDN dejó de cachear.",
      "A middleware added Set-Cookie everywhere, so the CDN stopped caching.",
    ],
    { p: 1 },
  ),
  S(
    "mtu",
    "edge",
    2,
    "pkt >1400B drop",
    ["Requests grandes cuelgan; las chicas no", "Big requests hang, small ones work"],
    [
      ["Revisar MTU y PMTUD", "Check MTU and PMTUD"],
      ["Subir el timeout", "Raise the timeout"],
      ["Reiniciar el LB", "Restart the LB"],
      ["Comprimir el payload", "Compress the payload"],
    ],
    [
      "El túnel tenía MTU 1400 y alguien bloqueó ICMP. PMTUD roto.",
      "The tunnel had MTU 1400 and someone blocked ICMP. PMTUD broken.",
    ],
    { p: 3 },
  ),
  S(
    "r53-health",
    "edge",
    2,
    "origin: dead/OK",
    ["Route 53 dice sano a un origen caído", "Route 53 says a dead origin is healthy"],
    [
      ["Health check a un endpoint real", "Health check a real endpoint"],
      ["Bajar el TTL a 1s", "Drop the TTL to 1s"],
      ["Reiniciar Route 53", "Restart Route 53"],
      ["Quitar el health check", "Remove the health check"],
    ],
    [
      "El check pegaba a /ping, que responde aunque la DB esté muerta.",
      "The check hit /ping, which answers even with the DB dead.",
    ],
  ),
  S(
    "tls-chain",
    "gw",
    2,
    "TLS err android",
    ["Android viejo falla TLS; iOS funciona", "Old Android fails TLS; iOS is fine"],
    [
      ["Servir la cadena intermedia", "Serve the intermediate chain"],
      ["Pedir que actualicen el celular", "Tell users to upgrade phones"],
      ["Desactivar TLS 1.3", "Disable TLS 1.3"],
      ["Escalar el gateway", "Scale the gateway"],
    ],
    [
      "El cert se instaló sin el intermedio; los clientes viejos no lo completan.",
      "The cert went in without the intermediate; old clients can't fill it in.",
    ],
  ),
  S(
    "conntrack",
    "k8s",
    2,
    "conntrack 100%",
    ["DNS falla al azar: conntrack lleno", "Random DNS failures: conntrack full"],
    [
      ["NodeLocal DNSCache", "NodeLocal DNSCache"],
      ["Reiniciar CoreDNS", "Restart CoreDNS"],
      ["Más réplicas de la app", "More app replicas"],
      ["IPs fijas en todo el código", "Hardcode IPs everywhere"],
    ],
    ["UDP a CoreDNS llenaba conntrack. Sí: DNS, otra vez.", "UDP to CoreDNS filled conntrack. Yes: DNS, again."],
    { p: 1 },
  ),
  S(
    "keepalive-502",
    "gw",
    3,
    "502 0.4%",
    ["502 esporádicos en conexiones keep-alive", "Sporadic 502s on keep-alive connections"],
    [
      ["Keep-alive app > idle del LB", "App keep-alive > LB idle timeout"],
      ["Reintentar todo 5 veces", "Retry everything 5 times"],
      ["Desactivar keep-alive", "Disable keep-alive"],
      ["Cambiar de LB", "Switch load balancers"],
    ],
    [
      "El ALB cortaba a los 60s y Node a los 5s: carrera clásica.",
      "The ALB cut at 60s and Node at 5s: a classic race.",
    ],
    { p: 2 },
  ),
  S(
    "ddos",
    "edge",
    1,
    "RPS x40 /login",
    ["x40 requests a /login desde 9k IPs", "x40 requests to /login from 9k IPs"],
    [
      ["Rate limit + WAF en el edge", "Rate limit + WAF at the edge"],
      ["Escalar la API x40", "Scale the API x40"],
      ["Apagar el login", "Turn off login"],
      ["Bloquear IP por IP", "Block them IP by IP"],
    ],
    [
      "Se frena en el borde, no en tu cluster. Credential stuffing de manual.",
      "Stop it at the edge, not in your cluster. Textbook credential stuffing.",
    ],
    { p: 1 },
  ),
  S(
    "cdn-private",
    "edge",
    1,
    "wrong user page",
    ["El CDN muestra la cuenta de otro usuario", "CDN serves another user's account page"],
    [
      ["Purgar y marcar private, no-store", "Purge, mark private no-store"],
      ["Escalar el CDN", "Scale the CDN"],
      ["Esperar al TTL", "Wait for the TTL"],
      ["Que borren su caché", "Ask users to clear cache"],
    ],
    [
      "Una página con sesión se cacheó como pública. Esto es SEV1 y es legal.",
      "A logged-in page got cached as public. This is SEV1 and it's legal's too.",
    ],
  ),

  // ── Kubernetes ────────────────────────────────────────────────────────
  S(
    "cpu-dashboards",
    "k8s",
    2,
    "CPU 99%",
    ["CPU 99% en los pods de checkout", "CPU 99% on checkout pods"],
    [
      ["¿Agregar más dashboards?", "Add more dashboards?"],
      ["Perfilar el último deploy", "Profile the last deploy"],
      ["Silenciar la alerta", "Silence the alert"],
      ["Escribir el postmortem ya", "Write the postmortem now"],
    ],
    [
      "Un dashboard más no baja la CPU. Era un regex catastrófico.",
      "Another dashboard won't lower CPU. It was a catastrophic regex.",
    ],
    { c: 1 },
  ),
  S(
    "noisy-neighbor",
    "k8s",
    3,
    "CPU steal 38%",
    ["Latencia errática en un solo nodo", "Erratic latency on a single node"],
    [
      ["Cordon, drain y fijar limits", "Cordon, drain, set limits"],
      ["Reiniciar la app", "Restart the app"],
      ["Rollback", "Rollback"],
      ["Subir el timeout", "Raise the timeout"],
    ],
    [
      "Noisy neighbor: un batch sin limits se comía el nodo.",
      "Noisy neighbor: a batch job with no limits ate the node.",
    ],
  ),
  S(
    "friday-leak",
    "k8s",
    1,
    "OOMKilled x14",
    ["OOMKilled en loop tras el deploy del viernes", "OOMKilled loop after Friday's deploy"],
    [
      ["Subir el limit a 16Gi", "Raise limit to 16Gi"],
      ["Rollback con ArgoCD", "Roll back via ArgoCD"],
      ["Cron que reinicie cada hora", "Hourly restart cron"],
      ["Agregar swap", "Add swap"],
    ],
    [
      "Memory leak: rollback primero, heap dump después. Y no deploys el viernes.",
      "Memory leak: roll back first, heap dump later. And no Friday deploys.",
    ],
    { c: 1, p: 0, next: { ok: "leak-heap", miss: "leak-limits" } },
  ),
  S(
    "leak-heap",
    "k8s",
    2,
    "heap +40MB/h",
    ["Rollback estable. El leak sigue en el canary", "Rollback held. The leak lives on in canary"],
    [
      ["Heap dump del canary y comparar", "Heap dump the canary, diff it"],
      ["Redeploy el viernes 18:00", "Redeploy Friday at 6pm"],
      ["Limit a 16Gi y olvidarlo", "16Gi limit and forget it"],
      ["Cerrar el ticket", "Close the ticket"],
    ],
    [
      "El dump mostró un cache sin límite por tenant. Fix, canary y el lunes.",
      "The dump showed an unbounded per-tenant cache. Fix, canary, Monday.",
    ],
    { ...F, p: 2 },
  ),
  S(
    "leak-limits",
    "k8s",
    1,
    "node OOM x6",
    ["Con 16Gi el pod se come el nodo entero", "At 16Gi the pod eats the whole node"],
    [
      ["Rollback con ArgoCD ya", "Roll back via ArgoCD now"],
      ["Nodos de 64Gi", "Use 64Gi nodes"],
      ["Desactivar el OOM killer", "Disable the OOM killer"],
      ["Agregar swap", "Add swap"],
    ],
    [
      "Un leak crece hasta llenar lo que le des. Rollback primero.",
      "A leak grows into whatever you give it. Roll back first.",
    ],
    F,
  ),
  S(
    "hpa-max",
    "k8s",
    2,
    "replicas 20/20",
    ["HPA al máximo y la latencia sigue subiendo", "HPA maxed out, latency still climbing"],
    [
      ["maxReplicas a 200", "maxReplicas to 200"],
      ["Trazas del servicio lento", "Trace the slow dependency"],
      ["Reiniciar todo", "Restart everything"],
      ["Más dashboards", "More dashboards"],
    ],
    [
      "El cuello era un proveedor externo. Más pods, más conexiones colgadas.",
      "The bottleneck was a third party. More pods, more hung connections.",
    ],
    { c: 1, p: 0 },
  ),
  S(
    "crashloop",
    "k8s",
    2,
    "CrashLoopBackOff",
    ["CrashLoopBackOff tras cambiar un ConfigMap", "CrashLoopBackOff after a ConfigMap change"],
    [
      ["kubectl logs --previous", "kubectl logs --previous"],
      ["Borrar el namespace", "Delete the namespace"],
      ["Subir recursos", "Bump resources"],
      ["Más dashboards", "More dashboards"],
    ],
    ["Los logs previos mostraron un YAML con tabs. Clásico.", "Previous logs showed a YAML with tabs. Classic."],
  ),
  S(
    "my-machine",
    "k8s",
    2,
    "5xx 12%",
    ["5xx 12%; el dev dice «en mi máquina funciona»", "5xx 12%; dev says «works on my machine»"],
    [
      ["Llevar su laptop a prod", "Ship their laptop to prod"],
      ["Comparar config entre entornos", "Diff config across envs"],
      ["Rollback inmediato", "Immediate rollback"],
      ["Ignorar, solo es 12%", "Ignore, it's only 12%"],
    ],
    [
      "Prod tenía otro feature flag y una variable vacía. La laptop no escala.",
      "Prod had a different flag and an empty env var. The laptop doesn't scale.",
    ],
    { c: 1, p: 2 },
  ),
  S(
    "pdb-drain",
    "k8s",
    3,
    "drain stuck 2h",
    ["El upgrade de nodos lleva 2h atascado", "Node upgrade stuck for 2 hours"],
    [
      ["Buscar PDBs con 0 disrupciones", "Find PDBs allowing 0 disruptions"],
      ["Forzar delete de los pods", "Force-delete the pods"],
      ["Cancelar el upgrade para siempre", "Cancel the upgrade forever"],
      ["Agregar más nodos", "Add more nodes"],
    ],
    [
      "Un PDB minAvailable=1 con 1 réplica bloquea cualquier drain.",
      "A minAvailable=1 PDB on 1 replica blocks every drain.",
    ],
    { p: 1 },
  ),
  S(
    "image-pull",
    "k8s",
    2,
    "ImagePullBackOff",
    ["ImagePullBackOff en el deploy nuevo", "ImagePullBackOff on the new deploy"],
    [
      ["Revisar tag y credenciales ECR", "Check the tag and ECR creds"],
      ["Reiniciar el nodo", "Restart the node"],
      ["Borrar el deployment", "Delete the deployment"],
      ["Subir CPU", "Bump CPU"],
    ],
    [
      "El pipeline publicó :latest-fix y el manifiesto pedía :latest_fix.",
      "CI pushed :latest-fix and the manifest asked for :latest_fix.",
    ],
  ),
  S(
    "liveness-db",
    "k8s",
    1,
    "restarts 340",
    ["El liveness probe mata pods bajo carga", "Liveness probe kills pods under load"],
    [
      ["Liveness liviano, sin la DB", "Lightweight liveness, no DB"],
      ["Bajar el timeout del probe", "Lower the probe timeout"],
      ["Quitar todos los probes", "Remove every probe"],
      ["Escalar la DB", "Scale the DB"],
    ],
    [
      "El liveness consultaba la DB: DB lenta, pods reiniciando, cascada.",
      "Liveness queried the DB: slow DB, pods restarting, cascade.",
    ],
    { p: 2 },
  ),
  S(
    "karpenter-churn",
    "k8s",
    3,
    "nodes 120/h",
    ["Karpenter crea y borra nodos sin parar", "Karpenter churns nodes nonstop"],
    [
      ["Ajustar consolidación y PDBs", "Tune consolidation and PDBs"],
      ["Desinstalar Karpenter", "Uninstall Karpenter"],
      ["Volver a nodos a mano", "Go back to manual nodes"],
      ["Más instance types", "Allow more instance types"],
    ],
    [
      "Consolidación agresiva + pods sin PDB = nodos reciclados cada 5 minutos.",
      "Aggressive consolidation + no PDBs = nodes recycled every 5 minutes.",
    ],
  ),
  S(
    "etcd-quota",
    "k8s",
    1,
    "etcd 8GB",
    ["API server lento: etcd llegó a su cuota", "API server slow: etcd hit its quota"],
    [
      ["Compactar, defrag, buscar spam", "Compact, defrag, find spammer"],
      ["Reiniciar el control plane", "Restart the control plane"],
      ["Borrar namespaces al azar", "Delete random namespaces"],
      ["Agregar más workers", "Add more workers"],
    ],
    [
      "Un operador creaba un Event por segundo por pod. etcd no es un log.",
      "An operator emitted one Event per second per pod. etcd is not a log.",
    ],
  ),
  S(
    "evicted",
    "k8s",
    3,
    "Evicted 230",
    ["230 pods Evicted por disk pressure", "230 pods Evicted by disk pressure"],
    [
      ["Limitar ephemeral-storage", "Set ephemeral-storage limits"],
      ["Borrar los Evicted y listo", "Delete the Evicted, move on"],
      ["Disco de 2TB por nodo", "2TB disk per node"],
      ["Apagar el kubelet", "Turn off the kubelet"],
    ],
    [
      "Un pod escribía logs a /tmp sin límite. ephemeral-storage, por favor.",
      "A pod wrote logs to /tmp with no cap. ephemeral-storage, please.",
    ],
    { p: 1 },
  ),
  S(
    "hpa-flap",
    "k8s",
    3,
    "replicas 4↔40",
    ["El HPA oscila entre 4 y 40 réplicas", "HPA flaps between 4 and 40 replicas"],
    [
      ["Ventana de estabilización", "Add a stabilization window"],
      ["Fijar 40 réplicas para siempre", "Pin 40 replicas forever"],
      ["Borrar el HPA", "Delete the HPA"],
      ["Escalar por memoria", "Scale on memory instead"],
    ],
    [
      "Sin ventana, cada pico escala y cada valle borra. KubeCost lo notó.",
      "With no window, every spike scales up and every dip scales down. KubeCost noticed.",
    ],
    { p: 1 },
  ),
  S(
    "clock-skew",
    "k8s",
    2,
    "skew 4m",
    ["JWT inválidos: relojes de nodos 4 min off", "JWTs invalid: node clocks 4 min off"],
    [
      ["Revisar chrony/NTP en nodos", "Check chrony/NTP on nodes"],
      ["Leeway del JWT a 1 día", "Set JWT leeway to 1 day"],
      ["Rotar las llaves JWT", "Rotate the JWT keys"],
      ["Reiniciar Kong", "Restart Kong"],
    ],
    [
      "Una AMI nueva sin chrony. El tiempo también es infraestructura.",
      "A new AMI without chrony. Time is infrastructure too.",
    ],
  ),

  // ── API gateway and service mesh ─────────────────────────────────────
  S(
    "kong-429",
    "gw",
    2,
    "429 35%",
    ["Kong devuelve 429 al 35% de clientes", "Kong returns 429 to 35% of clients"],
    [
      ["Revisar el plugin rate-limiting", "Check the rate-limiting plugin"],
      ["Reiniciar Kong", "Restart Kong"],
      ["Escalar la API", "Scale the API"],
      ["Rollback de la DB", "Roll back the DB"],
    ],
    [
      "Limitaba por IP y un cliente entero salía por un solo NAT.",
      "It limited by IP and a whole client egressed through one NAT.",
    ],
  ),
  S(
    "jwks",
    "gw",
    1,
    "401 22%",
    ["401 en 22% de requests tras rotar llaves JWT", "401 on 22% of requests after JWT key rotation"],
    [
      ["Revisar el JWKS cacheado en Kong", "Check Kong's cached JWKS"],
      ["Desactivar la autenticación", "Disable auth"],
      ["Reiniciar la DB", "Restart the DB"],
      ["Escalar réplicas", "Scale replicas"],
    ],
    [
      "Kong cacheaba el JWKS viejo. Las llaves se rotan con solapamiento.",
      "Kong cached the old JWKS. Rotate keys with overlap.",
    ],
  ),
  S(
    "mesh-ca",
    "gw",
    1,
    "mTLS fail 100%",
    ["Kuma: todo el tráfico mTLS falla de golpe", "Kuma: all mTLS traffic fails at once"],
    [
      ["Revisar la CA del mesh", "Check the mesh CA expiry"],
      ["Apagar mTLS en prod", "Turn off mTLS in prod"],
      ["Reiniciar todos los sidecars", "Restart every sidecar"],
      ["Escalar el control plane", "Scale the control plane"],
    ],
    [
      "Venció la CA raíz del mesh. Había alertas para las hojas, no para la CA.",
      "The mesh root CA expired. Leaf certs had alerts; the CA didn't.",
    ],
  ),
  S(
    "sidecar-boot",
    "gw",
    3,
    "conn refused @boot",
    ["La app falla al arrancar: sidecar no listo", "App fails at boot: sidecar not ready"],
    [
      ["Sidecar nativo / esperar proxy", "Native sidecar / wait for proxy"],
      ["sleep 30 en el entrypoint", "sleep 30 in the entrypoint"],
      ["Quitar el mesh", "Remove the mesh"],
      ["Escalar el sidecar", "Scale the sidecar"],
    ],
    [
      "La app arrancaba antes que el proxy. Los sidecars nativos ordenan el arranque.",
      "The app started before the proxy. Native sidecars order startup.",
    ],
    { p: 1 },
  ),
  S(
    "apisix-route",
    "gw",
    2,
    "404 100% /v2",
    ["Tras un deploy, /v2 da 404 en APISIX", "After a deploy, /v2 returns 404 on APISIX"],
    [
      ["Revisar prioridad de rutas", "Check route priority"],
      ["Reiniciar APISIX", "Restart APISIX"],
      ["Rollback de la DB", "Roll back the DB"],
      ["Publicar /v3", "Ship /v3"],
    ],
    ["Una ruta /v* nueva con más prioridad se tragaba /v2.", "A new /v* route with higher priority swallowed /v2."],
  ),
  S(
    "apigw-29s",
    "gw",
    2,
    "504 @ 29s",
    ["AWS API Gateway da 504 justo a los 29s", "AWS API Gateway 504s at exactly 29s"],
    [
      ["Volverlo async: 202 + polling", "Go async: 202 + polling"],
      ["Pedir más timeout a AWS", "Ask AWS for a longer timeout"],
      ["Más memoria al Lambda", "More memory for the Lambda"],
      ["Reintentar desde el cliente", "Retry from the client"],
    ],
    [
      "El reporte tarda 45s. 29s es el timeout de integración: mejor async.",
      "The report takes 45s. 29s is the integration timeout: go async.",
    ],
    { p: 1 },
  ),
  S(
    "retry-storm",
    "gw",
    1,
    "RPS x8",
    ["Tráfico x8 sin un usuario nuevo", "Traffic x8 with no new users"],
    [
      ["Backoff, jitter y retry budget", "Backoff, jitter, retry budget"],
      ["Escalar todo x8", "Scale everything x8"],
      ["Bloquear a todos los clientes", "Block every client"],
      ["Más dashboards", "More dashboards"],
    ],
    [
      "Cada capa reintentaba 3 veces: 3×3×3 = tormenta autoinfligida.",
      "Every layer retried 3 times: 3×3×3 = a self-inflicted storm.",
    ],
    { p: 1 },
  ),
  S(
    "circuit-breaker",
    "gw",
    2,
    "upstream 5xx 90%",
    ["El proveedor de pagos responde 5xx", "The payment provider returns 5xx"],
    [
      ["Circuit breaker y modo degradado", "Circuit breaker, degraded mode"],
      ["Reintentar en loop", "Retry in a loop"],
      ["Rollback de nuestro deploy", "Roll back our deploy"],
      ["Escalar nuestros pods", "Scale our pods"],
    ],
    [
      "No es tuyo, pero el impacto sí. Abre el circuito y encola pagos.",
      "Not your bug, but your impact. Open the circuit, queue payments.",
    ],
  ),
  S(
    "kong-plugin",
    "gw",
    3,
    "p99 +400ms",
    ["Kong suma 400ms tras activar un plugin", "Kong adds 400ms after a new plugin"],
    [
      ["Perfilar el I/O del plugin", "Profile the plugin's I/O"],
      ["Escalar Kong x3", "Scale Kong x3"],
      ["Quitar Kong", "Remove Kong"],
      ["Bajar el log level", "Lower the log level"],
    ],
    [
      "El plugin de logging hacía HTTP síncrono por request. Usa un buffer.",
      "The logging plugin did a synchronous HTTP call per request. Buffer it.",
    ],
    { p: 1 },
  ),
  S(
    "cors",
    "gw",
    3,
    "preflight 403",
    ["CORS: el front no carga tras mover el dominio", "CORS: frontend breaks after a domain move"],
    [
      ["Agregar el nuevo origen", "Add the new origin"],
      ["Allow-Origin: * con cookies", "Allow-Origin: * with cookies"],
      ["Que desactiven CORS", "Tell users to disable CORS"],
      ["Reiniciar el CDN", "Restart the CDN"],
    ],
    [
      "Una línea en la allowlist. El comodín con credenciales ni funciona.",
      "One line in the allowlist. A wildcard with credentials doesn't even work.",
    ],
  ),

  // ── Databases and caches ─────────────────────────────────────────────
  S(
    "pg-pool",
    "db",
    1,
    "conns 500/500",
    ["Pool de conexiones a Postgres agotado", "Postgres connection pool exhausted"],
    [
      ["Reiniciar la DB", "Restart the DB"],
      ["PgBouncer y pool por pod menor", "PgBouncer, smaller pod pools"],
      ["Escalar réplicas de la API", "Scale API replicas"],
      ["Revisar trazas", "Check traces"],
    ],
    [
      "Cada réplica abría 50 conexiones; escalar la API lo empeoraba.",
      "Each replica opened 50 connections; scaling the API made it worse.",
    ],
    { c: 1, p: 3, next: { ok: "pgbouncer-prepared", miss: "pg-again" } },
  ),
  S(
    "pgbouncer-prepared",
    "db",
    2,
    "prepared stmt err",
    ["PgBouncer listo; fallan prepared statements", "PgBouncer up; prepared statements fail"],
    [
      ["Ajustar el driver al modo tx", "Fit the driver to tx pooling"],
      ["Volver a conexiones directas", "Go back to direct connections"],
      ["Reiniciar PgBouncer", "Restart PgBouncer"],
      ["max_connections a 5000", "max_connections to 5000"],
    ],
    [
      "En transaction mode hay que apagar prepared statements del driver.",
      "Transaction pooling means turning off driver prepared statements.",
    ],
    { ...F, p: 1 },
  ),
  S(
    "pg-again",
    "db",
    1,
    "conns 500/500",
    ["La DB volvió… y el pool se agota en 2 min", "DB is back… pool exhausted again in 2 min"],
    [
      ["PgBouncer y pools más chicos", "PgBouncer, smaller pools"],
      ["Reiniciar la DB otra vez", "Restart the DB again"],
      ["max_connections=10000", "max_connections=10000"],
      ["Escalar la API", "Scale the API"],
    ],
    [
      "Reiniciar vació el pool 2 minutos. La causa seguía ahí.",
      "The restart bought 2 minutes. The cause was still there.",
    ],
    F,
  ),
  S(
    "wal-disk",
    "db",
    1,
    "disk 97%",
    ["Disco de la DB al 97%", "DB disk at 97%"],
    [
      ["Borrar logs al azar", "Delete random logs"],
      ["Expandir volumen, revisar WAL", "Expand volume, check WAL"],
      ["Reiniciar la DB", "Restart the DB"],
      ["Escalar réplicas", "Scale replicas"],
    ],
    ["Un replication slot huérfano retenía el WAL.", "An orphaned replication slot was holding the WAL."],
    { c: 1 },
  ),
  S(
    "migration-lock",
    "db",
    1,
    "locks 1.8k",
    ["Una migración bloquea la tabla orders", "A migration is locking the orders table"],
    [
      ["Matar migración, usar CONCURRENTLY", "Kill it, use CONCURRENTLY"],
      ["Reiniciar la DB", "Restart the DB"],
      ["Escalar la API", "Scale the API"],
      ["Esperar que termine", "Wait for it to finish"],
    ],
    [
      "Un ALTER tomó lock exclusivo en hora pico. Índices: CONCURRENTLY.",
      "An ALTER took an exclusive lock at peak. Indexes: CONCURRENTLY.",
    ],
  ),
  S(
    "dynamo-hot",
    "db",
    2,
    "throttled 30%",
    ["DynamoDB throttlea con capacidad libre", "DynamoDB throttles with spare capacity"],
    [
      ["Repartir la partition key", "Spread the hot partition key"],
      ["Subir WCU x10", "Raise WCU x10"],
      ["Migrar a Postgres hoy", "Migrate to Postgres today"],
      ["Reintentar sin backoff", "Retry with no backoff"],
    ],
    [
      "Todas las escrituras usaban la fecha como key. Capacidad total ≠ por partición.",
      "Every write used today's date as key. Table capacity ≠ partition capacity.",
    ],
    { p: 1 },
  ),
  S(
    "replica-lag",
    "db",
    2,
    "replica lag 900s",
    ["Usuarios no ven el pedido que acaban de hacer", "Users can't see the order they just placed"],
    [
      ["Read-your-writes al primary", "Read-your-writes from primary"],
      ["Reiniciar la réplica", "Restart the replica"],
      ["Quitar la réplica", "Remove the replica"],
      ["Cachear 1h más", "Cache it for another hour"],
    ],
    ["Las lecturas iban a una réplica con 15 min de lag.", "Reads went to a replica 15 minutes behind."],
    { p: 1 },
  ),
  S(
    "vacuum",
    "db",
    3,
    "bloat 70%",
    ["Queries lentas y 70% de bloat en la tabla", "Slow queries, table at 70% bloat"],
    [
      ["Ajustar autovacuum / pg_repack", "Tune autovacuum / pg_repack"],
      ["VACUUM FULL en hora pico", "VACUUM FULL at peak"],
      ["Reiniciar Postgres", "Restart Postgres"],
      ["Más índices", "More indexes"],
    ],
    [
      "Autovacuum no alcanzaba a una tabla de 2B filas. VACUUM FULL bloquea todo.",
      "Autovacuum couldn't keep up with 2B rows. VACUUM FULL locks everything.",
    ],
  ),
  S(
    "xid-wrap",
    "db",
    1,
    "XID 1.9B",
    ["Postgres avisa: wraparound en 50M XIDs", "Postgres warns: wraparound in 50M XIDs"],
    [
      ["VACUUM urgente, matar tx viejas", "Urgent VACUUM, kill old txns"],
      ["Ignorar, quedan 50M", "Ignore it, 50M left"],
      ["Reiniciar la DB", "Restart the DB"],
      ["Borrar la tabla", "Drop the table"],
    ],
    ["Una transacción abierta hace 3 días bloqueaba el vacuum.", "A transaction open for 3 days was blocking vacuum."],
  ),
  S(
    "seq-scan",
    "db",
    3,
    "seq scan 40M",
    ["Un endpoint nuevo hace seq scan de 40M filas", "New endpoint seq-scans 40M rows"],
    [
      ["Índice con CONCURRENTLY", "Add an index CONCURRENTLY"],
      ["Escalar la DB x2", "Scale the DB x2"],
      ["Cachear 24h", "Cache it for 24h"],
      ["Reiniciar la DB", "Restart the DB"],
    ],
    ["EXPLAIN ANALYZE antes de comprar hardware.", "EXPLAIN ANALYZE before buying hardware."],
    { p: 1 },
  ),
  S(
    "rds-failover",
    "db",
    1,
    "writes fail 100%",
    ["Failover de RDS hecho; la app sigue al viejo", "RDS failed over; app still hits the old one"],
    [
      ["Bajar el DNS cache de la JVM", "Lower the JVM DNS cache TTL"],
      ["Failback manual", "Manual failback"],
      ["Reiniciar RDS otra vez", "Restart RDS again"],
      ["Abrir un ticket", "Open a ticket"],
    ],
    [
      "La JVM cacheaba DNS para siempre. networkaddress.cache.ttl. DNS, otra vez.",
      "The JVM cached DNS forever. networkaddress.cache.ttl. DNS, again.",
    ],
  ),
  S(
    "backup-restore",
    "db",
    1,
    "restore: untested",
    ["Borraron una tabla; el backup nunca se probó", "Table dropped; backup never tested"],
    [
      ["PITR a un clon y validar", "PITR to a clone, then validate"],
      ["Restaurar encima de prod", "Restore straight over prod"],
      ["Pedir perdón y rezar", "Apologize and pray"],
      ["Recrear la tabla vacía", "Recreate the table empty"],
    ],
    [
      "Restaurar en paralelo, validar y copiar. Y desde hoy: restores de prueba.",
      "Restore aside, validate, copy back. And from today: restore drills.",
    ],
  ),
  S(
    "cache-stampede",
    "cache",
    1,
    "hit rate 4%",
    ["Redis vacío tras un flush: la DB recibe todo", "Redis empty after a flush: DB takes it all"],
    [
      ["Reiniciar la DB", "Restart the DB"],
      ["Calentar cache con coalescing", "Warm cache with coalescing"],
      ["Escalar la DB vertical", "Scale the DB up"],
      ["Rollback", "Rollback"],
    ],
    [
      "Thundering herd. Coalescing y jitter en el TTL protegen la DB.",
      "Thundering herd. Coalescing and TTL jitter protect the DB.",
    ],
    { c: 1, p: 2 },
  ),
  S(
    "redis-evict",
    "cache",
    2,
    "evictions 9k/s",
    ["Redis expulsa keys: maxmemory alcanzado", "Redis evicting keys: maxmemory reached"],
    [
      ["Buscar keys sin TTL", "Find keys without TTL"],
      ["Reiniciar Redis", "Restart Redis"],
      ["Escalar la API", "Scale the API"],
      ["Rollback de Kafka", "Roll back Kafka"],
    ],
    [
      "Sesiones sin TTL llenaron Redis. Reiniciar solo borra la evidencia.",
      "Sessions without TTL filled Redis. Restarting just erases evidence.",
    ],
    { p: 1 },
  ),
  S(
    "redis-keys",
    "cache",
    2,
    "CPU 100% 1 core",
    ["Redis al 100% de CPU en un solo core", "Redis pinned at 100% on one core"],
    [
      ["Buscar KEYS * en el slowlog", "Find KEYS * in the slowlog"],
      ["Más vCPUs para Redis", "More vCPUs for Redis"],
      ["Reiniciar Redis", "Restart Redis"],
      ["Bajar el TTL", "Lower the TTL"],
    ],
    [
      "Un cron llamaba KEYS * cada minuto. Usa SCAN. Redis no paraleliza eso.",
      "A cron ran KEYS * every minute. Use SCAN. More cores won't help.",
    ],
  ),
  S(
    "hot-key",
    "cache",
    3,
    "1 key = 80% ops",
    ["Una sola key recibe 80% del tráfico", "One key takes 80% of the traffic"],
    [
      ["Cache local en la app", "Local in-process cache"],
      ["Más shards de Redis", "More Redis shards"],
      ["Borrar la key", "Delete the key"],
      ["Reiniciar Redis", "Restart Redis"],
    ],
    [
      "La config global se leía en cada request. Más shards no reparten una key.",
      "Global config was read on every request. Shards can't split one key.",
    ],
    { p: 1 },
  ),

  // ── Queues and streams ───────────────────────────────────────────────
  S(
    "kafka-lag",
    "stream",
    2,
    "lag 1.2M",
    ["Consumer lag de pagos en 1.2M", "Payments consumer lag at 1.2M"],
    [
      ["Más consumers (≤ particiones)", "More consumers (≤ partitions)"],
      ["Borrar el topic", "Delete the topic"],
      ["Reiniciar el broker", "Restart the broker"],
      ["Bajar la retención", "Lower retention"],
    ],
    ["12 particiones y 3 consumers. Con 12 el lag se drenó.", "12 partitions, 3 consumers. At 12 the lag drained."],
  ),
  S(
    "rebalance",
    "stream",
    2,
    "rebalances 40/min",
    ["Rebalances constantes del consumer group", "Consumer group keeps rebalancing"],
    [
      ["Lotes chicos o más max.poll", "Smaller batches or more max.poll"],
      ["Más particiones", "More partitions"],
      ["Reiniciar el cluster", "Restart the cluster"],
      ["Borrar el consumer group", "Delete the consumer group"],
    ],
    [
      "Procesar tardaba más que max.poll.interval.ms y el broker los expulsaba.",
      "Processing outlasted max.poll.interval.ms, so the broker kicked them.",
    ],
  ),
  S(
    "under-replicated",
    "stream",
    1,
    "URP 18",
    ["Particiones under-replicated en Kafka", "Under-replicated partitions in Kafka"],
    [
      ["Revisar el broker y su disco", "Check the broker and its disk"],
      ["Poner acks=0", "Set acks=0"],
      ["Borrar topics viejos", "Delete old topics"],
      ["Escalar la API", "Scale the API"],
    ],
    [
      "Un broker sin disco. acks=0 «arregla» la alerta como cerrar los ojos.",
      "A broker ran out of disk. acks=0 «fixes» it like closing your eyes.",
    ],
  ),
  S(
    "sqs-dlq",
    "stream",
    2,
    "DLQ 48k",
    ["La DLQ de SQS tiene 48k mensajes", "SQS DLQ holds 48k messages"],
    [
      ["Leer el error, fix, luego redrive", "Read the error, fix, then redrive"],
      ["Redrive de todo ya", "Redrive everything now"],
      ["Purgar la DLQ", "Purge the DLQ"],
      ["maxReceiveCount a 1000", "maxReceiveCount to 1000"],
    ],
    [
      "Un cambio de esquema rompía el parser. Redrive sin fix = DLQ otra vez.",
      "A schema change broke the parser. Redrive without a fix = DLQ again.",
    ],
  ),
  S(
    "sqs-visibility",
    "stream",
    2,
    "dup x3",
    ["Pedidos procesados 3 veces desde SQS", "Orders processed 3 times from SQS"],
    [
      ["Visibility > tiempo de proceso", "Visibility > processing time"],
      ["Cambiar a FIFO hoy", "Switch to FIFO today"],
      ["Borrar al leer, antes de procesar", "Delete on read, before work"],
      ["Más consumers", "More consumers"],
    ],
    [
      "Procesar tardaba 90s y el visibility timeout era 30s. E idempotencia, siempre.",
      "Processing took 90s, visibility was 30s. And idempotency, always.",
    ],
    { p: 1 },
  ),
  S(
    "eventbridge-loop",
    "stream",
    1,
    "events 2M/min",
    ["EventBridge: una regla se dispara a sí misma", "EventBridge: a rule keeps triggering itself"],
    [
      ["Deshabilitar la regla, filtrar", "Disable the rule, fix pattern"],
      ["Subir la cuota", "Raise the quota"],
      ["Esperar a que pare sola", "Wait for it to stop"],
      ["Escalar los Lambdas", "Scale the Lambdas"],
    ],
    [
      "El Lambda publicaba el mismo detail-type que escuchaba. Factura recursiva.",
      "The Lambda emitted the detail-type it listened to. A recursive bill.",
    ],
  ),
  S(
    "poison-msg",
    "stream",
    2,
    "offset stuck",
    ["Consumer atascado en el mismo offset", "Consumer stuck on the same offset"],
    [
      ["Mandar el mensaje veneno a DLQ", "Send the poison message to DLQ"],
      ["Reiniciar el consumer", "Restart the consumer"],
      ["Borrar el topic", "Delete the topic"],
      ["Más particiones", "More partitions"],
    ],
    [
      "Un JSON con un emoji en un campo numérico. Reiniciar lo relee igual.",
      "A JSON with an emoji in a number field. A restart just rereads it.",
    ],
    { p: 1 },
  ),
  S(
    "kafka-order",
    "stream",
    3,
    "out-of-order 4%",
    ["Eventos de una cuenta llegan desordenados", "One account's events arrive out of order"],
    [
      ["Key por account_id", "Key messages by account_id"],
      ["Una sola partición", "Use a single partition"],
      ["Ordenar en el front", "Sort them in the frontend"],
      ["Subir la retención", "Raise retention"],
    ],
    [
      "Sin key, round-robin entre particiones. El orden es por partición.",
      "No key means round-robin. Ordering is per partition.",
    ],
    { p: 1 },
  ),
  S(
    "kafka-retention",
    "stream",
    2,
    "retention 1h",
    ["Un consumer volvió y sus mensajes expiraron", "Consumer is back; its messages expired"],
    [
      ["Reprocesar desde el sink en S3", "Replay from the S3 sink"],
      ["Subir retención (ya tarde)", "Raise retention (too late)"],
      ["Inventar los datos", "Make up the data"],
      ["Reiniciar Kafka", "Restart Kafka"],
    ],
    [
      "Retención de 1h en un topic crítico. Por suerte, el sink a S3 tenía todo.",
      "1h retention on a critical topic. Luckily the S3 sink had it all.",
    ],
    { p: 1 },
  ),

  // ── Cloud provider ───────────────────────────────────────────────────
  S(
    "region-down",
    "cloud",
    1,
    "us-east-1 5xx 60%",
    ["Una región cae: 5xx 60% en us-east-1", "A region is down: 5xx 60% in us-east-1"],
    [
      ["Drenar tráfico a otra región", "Drain traffic to the other region"],
      ["Esperar a AWS", "Wait for AWS"],
      ["Reiniciar pods de la región", "Restart the region's pods"],
      ["Rollback", "Rollback"],
    ],
    [
      "Para esto es multi-región: drenar en el LB global y actualizar el status page.",
      "That's what multi-region is for: drain at the global LB, update the status page.",
    ],
    { next: { ok: "region-capacity", miss: "region-wait" } },
  ),
  S(
    "region-capacity",
    "cloud",
    1,
    "us-west-2 CPU 92%",
    ["Drenado listo; us-west-2 al 92% de CPU", "Drained; us-west-2 now at 92% CPU"],
    [
      ["Karpenter + apagar lo no crítico", "Karpenter + shed non-critical"],
      ["Volver a us-east-1", "Fail back to us-east-1"],
      ["Subir el timeout", "Raise the timeout"],
      ["Esperar que baje", "Wait for it to drop"],
    ],
    [
      "Load shedding: recomendaciones y reportes esperan; checkout no.",
      "Load shedding: recommendations and reports can wait; checkout can't.",
    ],
    F,
  ),
  S(
    "region-wait",
    "cloud",
    1,
    "down 40 min",
    ["40 min esperando a AWS; los clientes se van", "40 min waiting on AWS; customers leave"],
    [
      ["Drenar región y avisar en status", "Drain region, update status"],
      ["Seguir esperando", "Keep waiting"],
      ["Reiniciar los pods otra vez", "Restart the pods again"],
      ["Abrir otro ticket", "Open another ticket"],
    ],
    ["Tenías otra región pagada y ociosa. Úsala.", "You had another region, paid for and idle. Use it."],
    F,
  ),
  S(
    "az-degraded",
    "cloud",
    1,
    "use1-az4 err",
    ["Una AZ de AWS degradada", "One AWS AZ degraded"],
    [
      ["Drenar la AZ, escalar en las otras", "Drain the AZ, scale the others"],
      ["Esperar el status de AWS", "Wait for the AWS status"],
      ["Migrar a GCP hoy", "Migrate to GCP today"],
      ["Reiniciar todo", "Restart everything"],
    ],
    [
      "El status page de AWS siempre llega tarde. Tus métricas no.",
      "The AWS status page is always late. Your metrics aren't.",
    ],
    { p: 1 },
  ),
  S(
    "spot-reclaim",
    "cloud",
    2,
    "spot interrupts 18",
    ["AWS reclamó 18 nodos spot a la vez", "AWS reclaimed 18 spot nodes at once"],
    [
      ["Diversificar tipos + base on-demand", "Diversify types, on-demand base"],
      ["Prohibir spot para siempre", "Ban spot forever"],
      ["Abrir ticket a AWS", "Open a ticket with AWS"],
      ["Reiniciar los pods", "Restart the pods"],
    ],
    [
      "Un solo instance type en una AZ. Diversifica y deja una base on-demand.",
      "One instance type in one AZ. Diversify and keep an on-demand base.",
    ],
    { p: 1 },
  ),
  S(
    "cidr-exhaust",
    "cloud",
    2,
    "free IPs 0",
    ["Pods en Pending: la subred no tiene IPs", "Pods Pending: subnet out of IPs"],
    [
      ["Prefix delegation o subred extra", "Prefix delegation or new subnet"],
      ["Borrar pods viejos", "Delete old pods"],
      ["Reiniciar el CNI", "Restart the CNI"],
      ["Una /8 para todo", "One /8 for everything"],
    ],
    [
      "El VPC CNI reserva IPs por nodo y Karpenter lanzó 40 nodos chicos.",
      "The VPC CNI reserves IPs per node, and Karpenter launched 40 small ones.",
    ],
  ),
  S(
    "gke-quota",
    "cloud",
    2,
    "CPUS quota 100%",
    ["GKE no escala: cuota regional de CPUs", "GKE won't scale: regional CPU quota"],
    [
      ["Pedir cuota, usar región B", "Request quota, burst to region B"],
      ["Borrar nodos de otro equipo", "Delete another team's nodes"],
      ["Reiniciar GKE", "Restart GKE"],
      ["Requests en 0", "Set requests to 0"],
    ],
    ["La cuota se pide antes del Black Friday, no durante.", "Quota is requested before Black Friday, not during."],
  ),
  S(
    "ebs-attach",
    "cloud",
    2,
    "Multi-Attach error",
    ["Pod con PVC no arranca: volumen en otro nodo", "PVC pod stuck: volume on another node"],
    [
      ["Liberar el VolumeAttachment viejo", "Free the stale VolumeAttachment"],
      ["Borrar el PVC", "Delete the PVC"],
      ["Volumen nuevo vacío", "Use a new empty volume"],
      ["Reiniciar el cluster", "Restart the cluster"],
    ],
    [
      "El nodo murió sin desmontar. Borrar el PVC borra los datos.",
      "The node died without detaching. Deleting the PVC deletes the data.",
    ],
  ),
  S(
    "lb-limit",
    "cloud",
    3,
    "LBs 50/50",
    ["No se crean más LoadBalancers: límite", "Can't create LoadBalancers: limit hit"],
    [
      ["Ingress compartido + pedir cuota", "Shared ingress + request quota"],
      ["Una cuenta AWS por servicio", "One AWS account per service"],
      ["NodePort a internet", "NodePort to the internet"],
      ["Borrar LBs de staging", "Delete staging's LBs"],
    ],
    [
      "Un Service type LoadBalancer por microservicio. Un ingress los une.",
      "One LoadBalancer Service per microservice. One ingress unites them.",
    ],
    { p: 3 },
  ),
  S(
    "lambda-throttle",
    "cloud",
    2,
    "throttles 12k",
    ["Lambdas throttleados en toda la cuenta", "Lambdas throttled account-wide"],
    [
      ["Reserved concurrency al culpable", "Reserved concurrency on culprit"],
      ["Pedir cuota y esperar", "Request quota and wait"],
      ["Migrar todo a EC2", "Move everything to EC2"],
      ["Reintentar más", "Retry harder"],
    ],
    [
      "Un batch consumía las 1000 ejecuciones y dejó sin aire a la API.",
      "A batch used all 1000 executions and starved the API.",
    ],
    { p: 1 },
  ),
  S(
    "lambda-cold",
    "cloud",
    3,
    "init p99 6s",
    ["Cold starts de 6s en el login", "6s cold starts on login"],
    [
      ["Provisioned concurrency/SnapStart", "Provisioned concurrency/SnapStart"],
      ["Cron que lo pinguee", "A cron that pings it"],
      ["Más dashboards", "More dashboards"],
      ["Reescribir en Rust hoy", "Rewrite it in Rust today"],
    ],
    [
      "Java + Spring en Lambda. SnapStart o concurrencia provisionada en el login.",
      "Java + Spring on Lambda. SnapStart or provisioned concurrency for login.",
    ],
    { p: 1 },
  ),

  // ── Observability ────────────────────────────────────────────────────
  S(
    "api-latency",
    "obs",
    2,
    "p99 3500ms",
    ["Latencia API p99 3500ms", "API latency p99 3500ms"],
    [
      ["Escalar réplicas", "Scale replicas"],
      ["Reiniciar DB", "Restart DB"],
      ["Rollback", "Rollback"],
      ["Revisar trazas", "Check traces"],
    ],
    ["Las trazas en Tempo mostraron un N+1 contra la DB.", "Tempo traces showed an N+1 against the DB."],
    { c: 3, p: 0 },
  ),
  S(
    "cardinality",
    "obs",
    2,
    "series 4.1M",
    ["Prometheus OOM: cardinalidad explotó", "Prometheus OOM: cardinality exploded"],
    [
      ["Darle 64GB a Prometheus", "Give Prometheus 64GB"],
      ["Quitar el label user_id", "Drop the user_id label"],
      ["Borrar los dashboards", "Delete the dashboards"],
      ["Reiniciarlo cada hora", "Restart it hourly"],
    ],
    [
      "Alguien puso user_id como label. 4 millones de series después…",
      "Someone used user_id as a label. 4 million series later…",
    ],
    { c: 1, p: 0 },
  ),
  S(
    "alert-fatigue",
    "obs",
    3,
    "312 alerts/h",
    ["312 alertas por hora y nadie las lee", "312 alerts an hour and nobody reads them"],
    [
      ["Silenciar el canal", "Mute the channel"],
      ["Alertar por SLO burn rate", "Alert on SLO burn rate"],
      ["Agregar más alertas", "Add more alerts"],
      ["Contratar a alguien que las lea", "Hire someone to read them"],
    ],
    [
      "Alerta por síntomas y error budget, no por cada CPU al 80%.",
      "Alert on symptoms and error budget, not every CPU at 80%.",
    ],
    { c: 1 },
  ),
  S(
    "loki-429",
    "obs",
    3,
    "ingest 429",
    ["Loki rechaza logs por rate limit", "Loki is rejecting logs: rate limited"],
    [
      ["Buscar quién loguea 10x", "Find who logs 10x more"],
      ["Límite infinito en Loki", "Set Loki's limit to infinite"],
      ["Apagar los logs", "Turn off logging"],
      ["Reiniciar Loki", "Restart Loki"],
    ],
    ["Un log de debug dentro de un loop: 40k líneas por segundo.", "A debug log inside a loop: 40k lines a second."],
    { p: 1 },
  ),
  S(
    "tempo-sampling",
    "obs",
    3,
    "traces 0.01%",
    ["No hay trazas del error de checkout", "No traces of the checkout error"],
    [
      ["Tail sampling por errores", "Tail sampling on errors"],
      ["Sampling 100% para todo", "100% sampling for everything"],
      ["Agregar console.log", "Add console.log"],
      ["Más dashboards", "More dashboards"],
    ],
    [
      "Head sampling al 0.01% descarta justo lo raro. Tail sampling guarda errores.",
      "0.01% head sampling drops exactly the weird ones. Tail sampling keeps errors.",
    ],
    { p: 1 },
  ),
  S(
    "no-data",
    "obs",
    1,
    "no data 2h",
    ["Dashboards en verde… sin datos hace 2h", "Dashboards green… with no data for 2h"],
    [
      ["Alerta absent() / dead man switch", "Alert on absent(), dead man switch"],
      ["Celebrar: cero errores", "Celebrate: zero errors"],
      ["Reiniciar Grafana", "Restart Grafana"],
      ["Cambiar los colores", "Change the colors"],
    ],
    [
      "El remote_write llevaba 2h caído. Sin datos no es sin errores.",
      "remote_write had been down for 2h. No data isn't no errors.",
    ],
  ),

  // ── Cost and FinOps ──────────────────────────────────────────────────
  S(
    "nat-cost",
    "cost",
    2,
    "+$4.2k/day",
    ["Cost spike: NAT Gateway", "Cost spike: NAT Gateway"],
    [
      ["VPC endpoints para S3/ECR", "VPC endpoints for S3/ECR"],
      ["Apagar el NAT", "Turn off the NAT"],
      ["Cambiar de región", "Switch regions"],
      ["Pedir más presupuesto", "Ask for more budget"],
    ],
    [
      "Pulls de imágenes y S3 salían por el NAT. Endpoints y listo.",
      "Image pulls and S3 went through the NAT. Endpoints fixed it.",
    ],
  ),
  S(
    "cross-az",
    "cost",
    3,
    "cross-AZ 80TB",
    ["La transferencia entre AZs se triplicó", "Cross-AZ transfer bill tripled"],
    [
      ["Topology-aware routing", "Topology-aware routing"],
      ["Todo a una sola AZ", "Move everything to one AZ"],
      ["Apagar réplicas de la DB", "Turn off DB replicas"],
      ["Cambiar de nube", "Switch clouds"],
    ],
    [
      "El tráfico pod a pod cruzaba zonas. Routing por topología, HA intacta.",
      "Pod-to-pod traffic crossed zones. Topology routing, HA intact.",
    ],
    { p: 1 },
  ),
  S(
    "idle-gpu",
    "cost",
    3,
    "GPU idle 94%",
    ["8 nodos GPU al 6% desde hace un mes", "8 GPU nodes at 6% for a month"],
    [
      ["KubeCost: dueño y escalar a 0", "KubeCost: find owner, scale to 0"],
      ["Esperar al próximo trimestre", "Wait for next quarter"],
      ["Comprar reserved instances", "Buy reserved instances"],
      ["Minar cripto con ellas", "Mine crypto with them"],
    ],
    [
      "Un POC de ML de hace un mes. KubeCost mostró el namespace; nadie lo apagó.",
      "A month-old ML POC. KubeCost showed the namespace; nobody turned it off.",
    ],
  ),
  S(
    "overprovision",
    "cost",
    3,
    "CPU req 8x use",
    ["Requests de CPU 8 veces el uso real", "CPU requests at 8x real usage"],
    [
      ["Rightsizing con datos de VPA", "Rightsize with VPA data"],
      ["Quitar todos los requests", "Remove all requests"],
      ["Más nodos por si acaso", "More nodes, just in case"],
      ["Pedir descuento al CFO", "Ask the CFO for a discount"],
    ],
    [
      "Requests copiados de un template de 2019. Karpenter empaca lo que pides.",
      "Requests copied from a 2019 template. Karpenter packs what you ask for.",
    ],
  ),
  S(
    "log-bucket",
    "cost",
    3,
    "S3 +2PB",
    ["El bucket de logs creció 2PB", "The logs bucket grew 2PB"],
    [
      ["Lifecycle a Glacier y expirar", "Lifecycle to Glacier + expiry"],
      ["Borrar el bucket", "Delete the bucket"],
      ["Comprimir a mano", "Compress it by hand"],
      ["Nada, S3 es barato", "Nothing, S3 is cheap"],
    ],
    [
      "Logs de debug sin lifecycle desde 2019. S3 es barato hasta que no.",
      "Debug logs with no lifecycle since 2019. S3 is cheap until it isn't.",
    ],
  ),
  S(
    "egress",
    "cost",
    2,
    "egress $11k/day",
    ["Egress a internet: $11k por día", "Internet egress: $11k a day"],
    [
      ["CDN delante de los assets", "Put a CDN in front of assets"],
      ["Bloquear todas las descargas", "Block all downloads"],
      ["Cambiar de región", "Switch regions"],
      ["Pedir más presupuesto", "Ask for more budget"],
    ],
    [
      "Un bucket servía videos directo. El CDN cuesta menos que egress de S3.",
      "A bucket served videos directly. A CDN costs less than S3 egress.",
    ],
  ),
  S(
    "savings-plan",
    "cost",
    3,
    "on-demand 92%",
    ["92% del cómputo estable es on-demand", "92% of steady compute is on-demand"],
    [
      ["Savings Plan sobre la base estable", "Savings Plan on the steady base"],
      ["Comprar 3 años para todo", "Buy 3 years for everything"],
      ["Todo a spot, hasta la DB", "Everything on spot, DB too"],
      ["Nada, así es flexible", "Nothing, it's flexible"],
    ],
    [
      "Compromete lo estable, deja flexible el pico. FinOps no es apostar.",
      "Commit the baseline, keep peaks flexible. FinOps isn't gambling.",
    ],
    { p: 1 },
  ),
  S(
    "demo-2021",
    "cost",
    3,
    "env: demo-2021",
    ["El entorno «demo-2021» cuesta $9k al mes", "A «demo-2021» env costs $9k a month"],
    [
      ["Confirmar dueño, terraform destroy", "Confirm owner, terraform destroy"],
      ["Borrarlo desde la consola", "Delete it from the console"],
      ["Dejarlo, por si acaso", "Keep it, just in case"],
      ["Renombrarlo a demo-2026", "Rename it demo-2026"],
    ],
    [
      "La demo fue hace 5 años. Destroy por Terraform, sin drift.",
      "The demo was 5 years ago. Destroy via Terraform, no drift.",
    ],
    { p: 1 },
  ),
  S(
    "metrics-bill",
    "cost",
    3,
    "$38k/mo metrics",
    ["La factura de métricas supera la de cómputo", "Metrics bill exceeds the compute bill"],
    [
      ["Recortar labels y retención", "Trim labels and retention"],
      ["Apagar Prometheus", "Turn off Prometheus"],
      ["Cambiar de vendor ya", "Switch vendors right now"],
      ["Pedir más presupuesto", "Ask for more budget"],
    ],
    [
      "Histogramas con 40 buckets y pod_name en todo. Observar no es guardar todo.",
      "40-bucket histograms with pod_name on everything. Observing isn't hoarding.",
    ],
    { p: 2 },
  ),

  // ── Security ─────────────────────────────────────────────────────────
  S(
    "aws-key-leak",
    "sec",
    1,
    "AKIA… public",
    ["Una access key de AWS en un repo público", "AWS access key in a public repo"],
    [
      ["Revocar y rotar ya", "Revoke and rotate now"],
      ["Borrar el commit y listo", "Delete the commit, done"],
      ["Hacer el repo privado", "Make the repo private"],
      ["Esperar a ver si la usan", "Wait and see if it's used"],
    ],
    [
      "Los bots escanean GitHub en segundos. Borrar el commit no revoca la key.",
      "Bots scan GitHub in seconds. Deleting the commit doesn't revoke the key.",
    ],
    { p: 1, next: { ok: "key-cloudtrail", miss: "key-mining" } },
  ),
  S(
    "key-cloudtrail",
    "sec",
    1,
    "GPU x200 sa-east-1",
    ["Key revocada. CloudTrail: 200 GPUs en sa-east-1", "Key revoked. CloudTrail: 200 GPUs in sa-east-1"],
    [
      ["Terminar + SCP de regiones", "Terminate + region-deny SCP"],
      ["Dejarlas, ya se pagaron", "Keep them, they're paid for"],
      ["Abrir ticket y esperar", "Open a ticket and wait"],
      ["Cambiar la clave de root", "Change the root password"],
    ],
    [
      "Termina, bloquea regiones que no usas y pide crédito a AWS.",
      "Terminate, deny regions you don't use, ask AWS for credit.",
    ],
    { ...F, p: 3 },
  ),
  S(
    "key-mining",
    "sec",
    1,
    "$48k in 6h",
    ["La key sigue viva: minan cripto en 6 regiones", "Key still live: crypto mining in 6 regions"],
    [
      ["Revocar, terminar, SCP", "Revoke, terminate, SCP"],
      ["Borrar el repo", "Delete the repo"],
      ["Esperar la factura", "Wait for the invoice"],
      ["Bloquear GitHub en la oficina", "Block GitHub at the office"],
    ],
    [
      "Cada minuto cuesta. La key primero, después todo lo demás.",
      "Every minute costs money. The key first, then everything else.",
    ],
    F,
  ),
  S(
    "cve-10",
    "sec",
    1,
    "CVSS 10.0",
    ["CVE crítico en una librería de logging", "Critical CVE in a logging library"],
    [
      ["SBOM, regla WAF y parche", "SBOM, WAF rule, then patch"],
      ["Esperar al próximo sprint", "Wait for next sprint"],
      ["Apagar todos los logs", "Turn off all logging"],
      ["Tuitear que no nos afecta", "Tweet that we're not affected"],
    ],
    [
      "Primero saber dónde está (SBOM), mitigar en el WAF, parchear.",
      "First know where it is (SBOM), mitigate at the WAF, patch.",
    ],
  ),
  S(
    "s3-public",
    "sec",
    1,
    "bucket: public",
    ["Un bucket con datos de clientes es público", "A bucket with customer data is public"],
    [
      ["Block Public Access y auditar", "Block Public Access, audit logs"],
      ["Renombrar el bucket", "Rename the bucket"],
      ["Esperar al lunes", "Wait until Monday"],
      ["Borrar los datos", "Delete the data"],
    ],
    [
      "Bloquea, revisa access logs para saber quién leyó y llama a legal.",
      "Block it, read access logs to see who read it, call legal.",
    ],
  ),
  S(
    "tokens-in-logs",
    "sec",
    2,
    "tokens in Loki",
    ["Tokens de usuarios aparecen en Loki", "User tokens are showing up in Loki"],
    [
      ["Redactar, rotar y purgar logs", "Redact, rotate, purge logs"],
      ["Hacer privado el dashboard", "Make the dashboard private"],
      ["Retención de 1 día", "Set retention to 1 day"],
      ["Nada, Loki es interno", "Nothing, Loki is internal"],
    ],
    [
      "Un middleware logueaba headers completos. Internal no es seguro.",
      "A middleware logged full headers. Internal isn't secure.",
    ],
    { p: 1 },
  ),
  S(
    "vault-sealed",
    "sec",
    1,
    "vault: sealed",
    ["Vault se selló al reiniciar; nada arranca", "Vault sealed on restart; nothing boots"],
    [
      ["Unseal con quórum de llaves", "Unseal with the key quorum"],
      ["Reinstalar Vault", "Reinstall Vault"],
      ["Secrets en ConfigMaps", "Put secrets in ConfigMaps"],
      ["Reiniciar otra vez", "Restart it again"],
    ],
    [
      "El auto-unseal usaba una llave KMS que alguien programó para borrar.",
      "Auto-unseal used a KMS key someone had scheduled for deletion.",
    ],
  ),
  S(
    "ci-admin",
    "sec",
    3,
    "Action: *",
    ["Un rol de CI tiene AdministratorAccess", "A CI role has AdministratorAccess"],
    [
      ["Mínimo privilegio + Access Analyzer", "Least privilege, Access Analyzer"],
      ["Dejarlo, funciona", "Leave it, it works"],
      ["Quitar el CI", "Remove CI"],
      ["Crear otro rol Admin", "Create another Admin role"],
    ],
    [
      "Access Analyzer genera la política real desde CloudTrail.",
      "Access Analyzer builds the real policy from CloudTrail.",
    ],
  ),

  // ── CI/CD and GitOps ─────────────────────────────────────────────────
  S(
    "argocd-drift",
    "ci",
    2,
    "OutOfSync 23",
    ["ArgoCD: 23 apps OutOfSync", "ArgoCD: 23 apps OutOfSync"],
    [
      ["kubectl edit en prod", "kubectl edit in prod"],
      ["Revisar el último merge GitOps", "Check the last GitOps merge"],
      ["Desinstalar ArgoCD", "Uninstall ArgoCD"],
      ["Apagar self-heal", "Disable self-heal"],
    ],
    [
      "Un merge cambió el chart base. En GitOps la verdad está en Git.",
      "A merge changed the base chart. In GitOps, Git is the truth.",
    ],
    { c: 1 },
  ),
  S(
    "argo-prune",
    "ci",
    1,
    "pruned: 41",
    ["ArgoCD borró 41 recursos de prod", "ArgoCD pruned 41 prod resources"],
    [
      ["Pausar auto-sync y revertir el PR", "Pause auto-sync, revert the PR"],
      ["kubectl apply desde tu laptop", "kubectl apply from your laptop"],
      ["Desinstalar ArgoCD", "Uninstall ArgoCD"],
      ["Esperar al self-heal", "Wait for self-heal"],
    ],
    [
      "Un refactor movió el path de kustomize; Argo vio cero recursos y podó.",
      "A refactor moved the kustomize path; Argo saw zero resources and pruned.",
    ],
    { p: 1 },
  ),
  S(
    "tf-lock",
    "ci",
    3,
    "state locked 3h",
    ["Terraform: state bloqueado hace 3 horas", "Terraform state locked for 3 hours"],
    [
      ["Confirmar que nadie corre, unlock", "Confirm no run, force-unlock"],
      ["Borrar el state", "Delete the state"],
      ["Editar el state a mano", "Hand-edit the state"],
      ["Crear otro state", "Start a new state"],
    ],
    [
      "Un job de CI murió con el lock tomado. Verifica y force-unlock.",
      "A CI job died holding the lock. Verify, then force-unlock.",
    ],
  ),
  S(
    "tf-destroy",
    "ci",
    1,
    "plan: -87",
    ["El plan de TF quiere destruir 87 recursos", "TF plan wants to destroy 87 resources"],
    [
      ["Parar, revisar moved/backend", "Stop, check moved/backend"],
      ["Apply, seguro está bien", "Apply, it's probably fine"],
      ["-target de uno en uno", "-target them one by one"],
      ["Auto-approve en CI", "Auto-approve in CI"],
    ],
    [
      "Un rename de módulo sin bloque moved {}. El plan siempre se lee.",
      "A module rename with no moved {} block. Always read the plan.",
    ],
    { p: 2 },
  ),
  S(
    "flaky-ci",
    "ci",
    3,
    "retry rate 40%",
    ["40% de pipelines pasan solo al reintentar", "40% of pipelines pass only on retry"],
    [
      ["Cuarentena de tests flaky", "Quarantine the flaky tests"],
      ["Retry automático x5", "Auto-retry x5"],
      ["Borrar los tests", "Delete the tests"],
      ["Mergear sin CI", "Merge without CI"],
    ],
    [
      "Sacarlos del camino crítico, con dueño y fecha. Retry x5 esconde bugs.",
      "Off the critical path, with an owner and date. Retry x5 hides bugs.",
    ],
    { p: 1 },
  ),
  S(
    "canary-bad",
    "ci",
    2,
    "canary 5xx 9%",
    ["El canary al 10% tiene 9% de errores", "Canary at 10% shows 9% errors"],
    [
      ["Abortar el rollout", "Abort the rollout"],
      ["Promoverlo al 100%", "Promote it to 100%"],
      ["Esperar más datos", "Wait for more data"],
      ["Apagar las métricas", "Turn off the metrics"],
    ],
    [
      "Para eso es el canary. Argo Rollouts aborta y casi nadie lo nota.",
      "That's what canaries are for. Argo Rollouts aborts; almost nobody notices.",
    ],
    { p: 2 },
  ),
  S(
    "helm-values",
    "ci",
    2,
    "replicas: 1",
    ["Un deploy dejó prod con 1 réplica", "A deploy left prod with 1 replica"],
    [
      ["Revisar values por entorno", "Check per-env Helm values"],
      ["Escalar a mano y seguir", "Scale by hand and move on"],
      ["Rollback de la DB", "Roll back the DB"],
      ["Reiniciar el cluster", "Restart the cluster"],
    ],
    [
      "values-prod.yaml no se incluía y se usaron los defaults de dev.",
      "values-prod.yaml wasn't included, so dev defaults shipped.",
    ],
    { p: 1 },
  ),
  S(
    "dockerhub-429",
    "ci",
    2,
    "429 docker.io",
    ["Docker Hub limita pulls: nodos nuevos fallan", "Docker Hub rate limit: new nodes fail"],
    [
      ["Pull-through cache en ECR", "Pull-through cache in ECR"],
      ["Crear 50 cuentas de Docker", "Create 50 Docker accounts"],
      ["Reiniciar los nodos", "Restart the nodes"],
      ["Esperar 6 horas", "Wait 6 hours"],
    ],
    [
      "Cada nodo nuevo de Karpenter bajaba la imagen base desde internet.",
      "Every new Karpenter node pulled the base image from the internet.",
    ],
    { p: 3 },
  ),
  S(
    "force-push",
    "ci",
    2,
    "main: -312 commits",
    ["Alguien hizo force push a main", "Someone force-pushed to main"],
    [
      ["Reflog, restaurar y proteger main", "Reflog, restore, protect main"],
      ["Despedir a alguien", "Fire someone"],
      ["Reescribir de memoria", "Rewrite it from memory"],
      ["Ignorarlo", "Ignore it"],
    ],
    [
      "Branch protection habría costado un clic. Blameless, pero con reglas.",
      "Branch protection was one click away. Blameless, but with rules.",
    ],
  ),

  // ── People and process ───────────────────────────────────────────────
  S(
    "bridge-47",
    "ops",
    1,
    "bridge: 47",
    ["47 personas en el bridge y nadie decide", "47 people on the bridge, nobody deciding"],
    [
      ["Nombrar IC, scribe y comms", "Name an IC, scribe, comms"],
      ["Invitar a más gente", "Invite more people"],
      ["Que todos revisen todo", "Everyone checks everything"],
      ["Abrir otro bridge", "Open a second bridge"],
    ],
    [
      "47 personas mirando el mismo dashboard no es redundancia.",
      "47 people staring at one dashboard isn't redundancy.",
    ],
    { next: { ok: "bridge-vp", miss: "bridge-83" } },
  ),
  S(
    "bridge-vp",
    "ops",
    2,
    "ETA?? x6",
    ["IC nombrado. Un VP pide ETA cada 5 min", "IC named. A VP asks for an ETA every 5 min"],
    [
      ["Comms: updates cada 30 min", "Comms posts updates every 30 min"],
      ["Inventar un ETA", "Make up an ETA"],
      ["Sacar al VP del bridge", "Kick the VP off the bridge"],
      ["Que el IC le responda todo", "IC answers every question"],
    ],
    [
      "Updates con hora fija: el VP se calma y el IC sigue trabajando.",
      "Updates on a fixed clock: the VP relaxes, the IC keeps working.",
    ],
    { ...F, p: 2 },
  ),
  S(
    "bridge-83",
    "ops",
    1,
    "bridge: 83",
    ["Ahora son 83 en el bridge y 4 hilos", "Now 83 on the bridge, 4 threads"],
    [
      ["Nombrar IC, scribe y comms", "Name an IC, scribe, comms"],
      ["Abrir un tercer bridge", "Open a third bridge"],
      ["Que hable el más senior", "Let the most senior talk"],
      ["Votación en Slack", "Run a Slack poll"],
    ],
    [
      "Sin roles el caos escala mejor que tu infraestructura.",
      "Without roles, chaos scales better than your infrastructure.",
    ],
    { ...F, p: 2 },
  ),
  S(
    "blame",
    "ops",
    3,
    "5 whys → Juan",
    ["El postmortem concluye: «fue culpa de Juan»", "Postmortem concludes: «Juan did it»"],
    [
      ["Blameless: arreglar el sistema", "Blameless: fix the system"],
      ["Quitarle acceso a Juan", "Revoke Juan's access"],
      ["Más aprobaciones manuales", "More manual approvals"],
      ["Cerrarlo y seguir", "Close it and move on"],
    ],
    [
      "Si Juan pudo romper prod con un comando, el sistema lo permitió.",
      "If Juan broke prod with one command, the system let him.",
    ],
    { p: 2 },
  ),
  S(
    "friday-deploy",
    "ops",
    3,
    "Fri 17:45",
    ["Viernes 17:45: «un deploy chiquito de config»", "Friday 5:45pm: «a tiny config deploy»"],
    [
      ["Lunes, detrás de un feature flag", "Monday, behind a feature flag"],
      ["Mandarlo y cerrar Slack", "Ship it and close Slack"],
      ["Solo si nadie mira", "Only if nobody's watching"],
      ["Mergear sin review", "Merge without review"],
    ],
    [
      "No existen los deploys chiquitos de config. Existe el lunes.",
      "There's no such thing as a tiny config deploy. There's Monday.",
    ],
  ),
  S(
    "status-green",
    "ops",
    2,
    "status: green",
    ["Twitter arde y el status page sigue verde", "Twitter is on fire, status page is green"],
    [
      ["Status y comms cada 30 min", "Status page + comms every 30 min"],
      ["Esperar a la causa raíz", "Wait for the root cause"],
      ["Borrar los tweets", "Delete the tweets"],
      ["Culpar al proveedor", "Blame the vendor"],
    ],
    [
      "Comunica lo que sabes ahora. La causa raíz puede esperar; la confianza no.",
      "Say what you know now. Root cause can wait; trust can't.",
    ],
    { p: 1 },
  ),
  S(
    "hero-oncall",
    "ops",
    3,
    "pages/wk 61",
    ["Una persona atendió 61 pages esta semana", "One person took 61 pages this week"],
    [
      ["Rotación justa y matar el ruido", "Fair rotation, kill the noise"],
      ["Regalarle una pizza", "Buy them a pizza"],
      ["Que siga, lo hace bien", "Let them, they're great at it"],
      ["Quitar el on-call", "Remove on-call"],
    ],
    [
      "Los héroes se queman. El ruido se arregla y la carga se reparte.",
      "Heroes burn out. Fix the noise and share the load.",
    ],
    { p: 1 },
  ),
  S(
    "runbook-404",
    "ops",
    2,
    "runbook: 404",
    ["El link del runbook de la alerta da 404", "The alert's runbook link is a 404"],
    [
      ["Mitigar y arreglar el runbook", "Mitigate, then fix the runbook"],
      ["Buscar al autor (renunció)", "Find the author (they quit)"],
      ["Esperar a alguien que sepa", "Wait for someone who knows"],
      ["Silenciar la alerta", "Silence the alert"],
    ],
    [
      "Mitiga con lo que ves y deja el runbook mejor que como lo encontraste.",
      "Mitigate with what you see; leave the runbook better than you found it.",
    ],
  ),
  S(
    "ssh-hotfix",
    "ops",
    2,
    "ssh prod-1",
    ["Alguien quiere hacer hotfix por SSH en prod", "Someone wants to SSH-hotfix prod"],
    [
      ["Hotfix por pipeline acelerado", "Hotfix via fast-track pipeline"],
      ["Dejarlo, es más rápido", "Let them, it's faster"],
      ["vim dentro del pod", "vim inside the pod"],
      ["Root para todos", "Root for everyone"],
    ],
    [
      "Un hotfix fuera de Git se pierde en el próximo deploy. Y ArgoCD lo revierte.",
      "A hotfix outside Git dies on the next deploy. And ArgoCD reverts it.",
    ],
    { p: 1 },
  ),
  S(
    "vacation-page",
    "ops",
    2,
    "ack 0/3",
    ["El SEV1 le llegó a alguien de vacaciones", "The SEV1 paged someone on vacation"],
    [
      ["Escalation policy con overrides", "Escalation policy with overrides"],
      ["Llamarle igual", "Call them anyway"],
      ["Apagar el pager", "Turn off the pager"],
      ["Culpar al calendario", "Blame the calendar"],
    ],
    [
      "Overrides y escalamiento automático. Las vacaciones son sagradas.",
      "Overrides and auto-escalation. Vacations are sacred.",
    ],
  ),
];

/** Index by id (for multi-step links). */
export const SCENARIO_INDEX: Record<string, number> = Object.fromEntries(SCENARIOS.map((s, i) => [s.id, i]));
