extends:
  - airbnb
  - plugin:import/recommended
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
plugins:
  - import
  - react
  - filenames
  - jsx-a11y
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    es6: true
    classes: true
    modules: true
env:
  browser: true
  es6: true
  node: true
  jest: true
rules:
  complexity: [0, 4]
  eqeqeq: 2
  filenames/match-regex: [2, "^[a-z-\\d\\.]+$", true]
  import/no-unresolved: 0
  import/first: "error"
  import/prefer-default-export: 0
  max-len:
    - "error"
    - 90
    - 1
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: false
      ignoreTemplateLiterals: false
  no-console: 1
  no-dupe-keys: 2
  no-else-return: 2
  no-empty: 2
  no-eq-null: 0
  no-extra-boolean-cast: 2
  no-extra-semi: 2
  no-mixed-spaces-and-tabs: 2
  no-param-reassign: 1
  no-redeclare: 2
  no-underscore-dangle: 2
  no-unreachable: 2
  no-unused-expressions: 0
  no-unused-vars: 2
  no-use-before-define: 2
  no-useless-constructor: 2
  no-useless-escape: 2
  object-curly-spacing: [2, always]
  object-shorthand:
    - 2
    - methods
    - ignoreConstructors: true
      avoidExplicitReturnArrows: true
  react/display-name: 0
  react/jsx-filename-extension: 0
  react/jsx-key: 1
  react/jsx-props-no-spreading:
    - 2
    - html: "ignore"
  react/no-array-index-key: 0
  react/no-unescaped-entities: 0
  react/prop-types: 0
  require-jsdoc: 0
  sort-imports: 0
  use-isnan: 2
