# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint:json
        continue-on-error: true

      - name: ESLint Report
        uses: ldiego73/eslint-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report: reports/lint.json

      - name: Unit Test
        run: yarn test:unit
